### ISSUE TITLE
Mastodon Bot stoped working on 31.01.23

### ISSUE THREAD

**Issue by boneffm** [solygen/node-sge-bot#3]
hi, the mastodon bot stoped working.
Last posts are from the 31.01. can you please give it a look?

**Comment by solygen** [comment]
Seems that the service i've used is no longer available
https://write.as/renatolond/timeline-for-the-shutdown-of-the-mastodon-twitter-crossposter-instance-at

I will try to move to mastodon completely by the end of the month (shutdown of twitters free api).
